apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: idea-helsinki
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: orchestrator
      context: .
      docker:
        dockerfile: services/orchestrator/Dockerfile
    - image: fcd-manager
      context: .
      docker:
        dockerfile: services/fcd-manager/Dockerfile
    - image: traffic-monitor
      context: .
      docker:
        dockerfile: services/traffic-monitor/Dockerfile
manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/secrets.yaml
    - k8s/influxdb-deployment.yaml
    - k8s/fake-gcs-server-deployment.yaml
    - k8s/idea-helsinki-deployment.yaml
    - k8s/fcd-manager-deployment.yaml
    - k8s/traffic-monitor-deployment.yaml
deploy:
  kubeContext: orbstack
  kubectl:
    defaultNamespace: idea-helsinki
    hooks:
      before:
        - host:
            command: ["sh", "-c", "dotenvx run -- sh scripts/generate-secrets.sh"]
