apiVersion: v1
kind: Secret
metadata:
  name: idea-helsinki-secrets
  namespace: idea-helsinki
type: Opaque
stringData:
  # Azure configuration
  AZURE_ACCOUNT_NAME: "fcdlidotiku"
  AZURE_CONTAINER_NAME: "tomtom"
  AZURE_SAS_TOKEN: "sp=rawl&st=2025-06-10T10:09:15Z&se=2025-12-31T19:09:15Z&spr=https&sv=2024-11-04&sr=c&sig=z0sB8GG1LOC39jXQQrsXSKWMBUnbb0XyJWGuL7y62q0%3D"

  # InfluxDB configuration
  INFLUX_DB_ORG: "idea-helsinki"
  INFLUX_DB_URL: "http://influxdb:8086"
  INFLUX_DB_FCD_BUCKET: "fcd-data"
  INFLUX_DB_FCD_TOKEN: "dev-token-changeme"
  INFLUX_DB_VALIDATION_BUCKET: "validation"
  INFLUX_DB_VALIDATION_TOKEN: "dev-token-changeme"

  # Sentry configuration (optional)
  SENTRY_DSN: "https://d96133badb991478a404ca60a43b37cc@o1161048.ingest.us.sentry.io/4510047203885056"
